name: Assemble and test Macho64

on:
  push:
    branches: [ main ]
    paths:
    - macho64.asm

  pull_request:
    branches: [ main ]
    paths:
    - macho64.asm

  workflow_dispatch:

jobs:
  assemble-and-test:
    runs-on: macos-latest
    steps:
    - uses: ilammy/setup-nasm@v1
    - name: Check out the codebase
      uses: actions/checkout@v2

    - name: assemble-executable
      run: nasm -fmacho64 macho64.asm && ld -e start -static macho64.o -o macho64

    - name: test-prints-helloworld
      run: if [[ "$(./macho64)" != "Hello, World" ]]; then exit 1; fi
